# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FunCZIDMSampler <- function(ITER, COUNTS, X, ID_END_IDX, RAND_EFF_COLS, BURN_IN = 0L, NUM_THIN = 1L, ADJ_FREQ = 250L, PROPOSAL_CAP = 0.75, ZI_GROUPED = TRUE, ADJ_PROPOSALS = TRUE, RETURN_BURN_IN = FALSE, CAP_PROPOSALS = FALSE, PRINT_PROGRESS = TRUE, TO_RETRUN = characterVector(), betaInitial = NULL, rInitial = NULL, priors = NULL, proposalVars = NULL) {
    .Call('_FunCZIDM_FunCZIDMSampler', PACKAGE = 'FunCZIDM', ITER, COUNTS, X, ID_END_IDX, RAND_EFF_COLS, BURN_IN, NUM_THIN, ADJ_FREQ, PROPOSAL_CAP, ZI_GROUPED, ADJ_PROPOSALS, RETURN_BURN_IN, CAP_PROPOSALS, PRINT_PROGRESS, TO_RETRUN, betaInitial, rInitial, priors, proposalVars)
}

getFit <- function(beta, basis, covariates) {
    .Call('_FunCZIDM_getFit', PACKAGE = 'FunCZIDM', beta, basis, covariates)
}

getSumExpFit <- function(fit) {
    .Call('_FunCZIDM_getSumExpFit', PACKAGE = 'FunCZIDM', fit)
}

getFitOfData <- function(beta, Xtv) {
    .Call('_FunCZIDM_getFitOfData', PACKAGE = 'FunCZIDM', beta, Xtv)
}

getRAFits <- function(beta, basis, covariates) {
    .Call('_FunCZIDM_getRAFits', PACKAGE = 'FunCZIDM', beta, basis, covariates)
}

getRAFitsPrecalc <- function(fit, sumExpFit) {
    .Call('_FunCZIDM_getRAFitsPrecalc', PACKAGE = 'FunCZIDM', fit, sumExpFit)
}

getBetaVC <- function(beta, VCRows, basis) {
    .Call('_FunCZIDM_getBetaVC', PACKAGE = 'FunCZIDM', beta, VCRows, basis)
}

getHillDiversity <- function(beta, basis, covariates, l = 0) {
    .Call('_FunCZIDM_getHillDiversity', PACKAGE = 'FunCZIDM', beta, basis, covariates, l)
}

getDeltaHillDiversity <- function(betaVCFits, fit, sumExpFit, l = 0, change = 1) {
    .Call('_FunCZIDM_getDeltaHillDiversity', PACKAGE = 'FunCZIDM', betaVCFits, fit, sumExpFit, l, change)
}

getAllCatDeltaRA <- function(betaVCFits, fit, sumExpFit, change = 1) {
    .Call('_FunCZIDM_getAllCatDeltaRA', PACKAGE = 'FunCZIDM', betaVCFits, fit, sumExpFit, change)
}

getDeltaRA <- function(cat, betaVCFits, fit, sumExpFit, change = 1) {
    .Call('_FunCZIDM_getDeltaRA', PACKAGE = 'FunCZIDM', cat, betaVCFits, fit, sumExpFit, change)
}

aitchison_distance <- function(xi, xj) {
    .Call('_FunCZIDM_aitchison_distance', PACKAGE = 'FunCZIDM', xi, xj)
}

getSignifCovProfileRA <- function(betaVCFits, betaVCFit, fit, sumExpFit, change = 1) {
    .Call('_FunCZIDM_getSignifCovProfileRA', PACKAGE = 'FunCZIDM', betaVCFits, betaVCFit, fit, sumExpFit, change)
}

getSignifCovProfileAlpha <- function(fit, fitBase, l = 0) {
    .Call('_FunCZIDM_getSignifCovProfileAlpha', PACKAGE = 'FunCZIDM', fit, fitBase, l)
}

getTrueVCRAFromMat <- function(betaNonVC, testPoints, catToCheck, funcInfo, xCenter = 0, interceptTV = FALSE) {
    .Call('_FunCZIDM_getTrueVCRAFromMat', PACKAGE = 'FunCZIDM', betaNonVC, testPoints, catToCheck, funcInfo, xCenter, interceptTV)
}

getTrueHillDivMultiChange <- function(baseFit, testPoints, funcInfo, l = 0, change = 1) {
    .Call('_FunCZIDM_getTrueHillDivMultiChange', PACKAGE = 'FunCZIDM', baseFit, testPoints, funcInfo, l, change)
}

